### ISSUE TITLE
tprm error 500

### ISSUE THREAD

**Issue by neocristal** [intuitem/ciso-assistant-community#3432]
**Describe the bug**
Traceback (most recent call last):

  File "/code/.venv/lib/python3.14/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/code/.venv/lib/python3.14/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper

    return view_func(request, *args, **kwargs)

  File "/code/.venv/lib/python3.14/site-packages/rest_framework/viewsets.py", line 125, in view

    return self.dispatch(request, *args, **kwargs)

           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/code/.venv/lib/python3.14/site-packages/rest_framework/views.py", line 515, in dispatch

    response = self.handle_exception(exc)

  File "/code/.venv/lib/python3.14/site-packages/rest_framework/views.py", line 475, in handle_exception

    self.raise_uncaught_exception(exc)

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^

  File "/code/.venv/lib/python3.14/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception

    raise exc

  File "/code/.venv/lib/python3.14/site-packages/rest_framework/views.py", line 512, in dispatch

    response = handler(request, *args, **kwargs)

  File "/code/tprm/views.py", line 771, in metrics

    "reviewers": ",".join([re.email for re in ea.reviewers.all()])

                           ^^^^^^^^

AttributeError: 'Actor' object has no attribute 'email'

Internal Server Error: /api/entity-assessments/metrics/

Traceback (most recent call last):

  File "/code/.venv/lib/python3.14/site-packages/django/core/handlers/exception.py", line 55, in inner

    response = get_response(request)

  File "/code/.venv/lib/python3.14/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/code/.venv/lib/python3.14/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper

    return view_func(request, *args, **kwargs)

  File "/code/.venv/lib/python3.14/site-packages/rest_framework/viewsets.py", line 125, in view

    return self.dispatch(request, *args, **kwargs)

           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/code/.venv/lib/python3.14/site-packages/rest_framework/views.py", line 515, in dispatch

    response = self.handle_exception(exc)

**To Reproduce**
Steps to reproduce the behavior:
1. Go to ['...'](/analytics/tprm)
2. Click on Third parties 'Overview'
3. Scroll down to '....'
4. See error Error 500
Internal Error

try change the line 771                 
"reviewers": ",".join([re.email for re in ea.reviewers.all()])
                if len(ea.reviewers.all())
                else "-",
To
"reviewers": ",".join([re.email for re in ea.representatives.all() if re.email]) if ea.representatives.exists() else "-"

**Expected behavior**
A clear and concise description of what you expected to happen. after update to 3.11.4

<img width="1018" height="706" alt="Image" src="https://github.com/user-attachments/assets/6c9ce8de-6a21-4763-a974-83562e2af5aa" />

**Comment by ab-smith** [comment]
thank you for reporting this. It's related to the fact that we missed updating the reviewers and authors of this object. will be fixed on the next release.
In the meantime and if the information is not critical for you, taking out the reviewers from the entity assessment should fix it temporarily.
